### ISSUE TITLE
migrate to pnpm

### ISSUE THREAD

**Issue by ekmas** [degen-space-organization/tg-bot-template#1]
dude no one is using yarn

**Comment by ekmas** [comment]
@Madjarx aj migriraj ovo na pnpm magarce

**Comment by Madjarx** [comment]
to su ti isti dinosaurusi magare, yarn superiorniji nemoj mi te tvoje off-white package managere da ne bi bilo belaja

**Comment by ekmas** [comment]
kog belaja druze, duzan si mi 2000 eura i jos se kurcis tu

**Comment by ekmas** [comment]
bolje samo migriraj na pnpm da ti ne dodjem i ne zapalim pola pazove

**Comment by Madjarx** [comment]
Evo seli smo predsednik opstine i ja i popricali, migriracemo po hitnom postupku
ovakve stvari se nece vise desavati

**Comment by ekmas** [comment]
hvala
